require('dotenv').config();
const pool = require('./pool');

// ═══════════════════════════════════════════════════════════
// MASTER DATA: City → Locality → Society
// Extracted from the uploaded Excel screenshot.
// To add more societies later, just add rows here and re-run:
//   node db/seed.js
// ═══════════════════════════════════════════════════════════

const SOCIETIES = [
  // ── GURGAON ──

  ["Gurgaon", "Ambience Island", "Ambience Lagoon"],
  ["Gurgaon", "Ardee City", "Ardee Palm Grove Heights"],
  ["Gurgaon", "Ardee City", "Ardee The Residency"],
  ["Gurgaon", "Chakkarpur", "Sahara Grace"],
  ["Gurgaon", "DLF Phase 1", "DLF Silver Oaks"],
  ["Gurgaon", "DLF Phase 1", "Silver Oaks Estates"],
  ["Gurgaon", "DLF Phase 2", "Emaar MGF The Vilas"],
  ["Gurgaon", "DLF Phase 2", "DLF Belvedere Park"],
  ["Gurgaon", "DLF Phase 2", "DLF Belvedere Towers"],
  ["Gurgaon", "DLF Phase 2", "DLF Oakwood Estate"],
  ["Gurgaon", "DLF Phase 2", "DLF Beverly Park"],
  ["Gurgaon", "DLF Phase 3", "Ambience Caitriona"],
  ["Gurgaon", "DLF Phase 4", "DLF Ridgewood Estate"],
  ["Gurgaon", "DLF Phase 4", "DLF Regency Park 2"],
  ["Gurgaon", "DLF Phase 4", "DLF Regency Park 1"],
  ["Gurgaon", "DLF Phase 4", "DLF Richmond Park"],
  ["Gurgaon", "DLF Phase 5", "DLF Westend Heights"],
  ["Gurgaon", "DLF Phase 5", "DLF Carlton Estate"],
  ["Gurgaon", "DLF Phase 5", "DLF Wellington Estate"],
  ["Gurgaon", "DLF Phase 5", "DLF Princeton Estate"],
  ["Gurgaon", "DLF Phase 5", "DLF The Pinnacle"],
  ["Gurgaon", "DLF Phase 5", "DLF The Icon"],
  ["Gurgaon", "DLF Phase 5", "DLF The Grove"],
  ["Gurgaon", "DLF Phase 5", "DLF Exclusive Floors"],
  ["Gurgaon", "DLF Phase 5", "DLF Trinity Towers"],
  ["Gurgaon", "Gwal Pahari", "Suncity Vatsal Valley"],
  ["Gurgaon", "Gwal Pahari", "Paras Quartier"],
  ["Gurgaon", "Gwal Pahari", "Valley View Estate"],
  ["Gurgaon", "Gwal Pahari", "Krrish Provence Estate"],
  ["Gurgaon", "Gwal Pahari", "ASF Isle De Royale"],
  ["Gurgaon", "Heritage City", "Unitech Heritage City"],
  ["Gurgaon", "Kadarpur", "Bedarwal Consortium Sixty Three Golf Drive"],
  ["Gurgaon", "locality", "society"],
  ["Gurgaon", "Malibu Town", "Malibu Towne"],
  ["Gurgaon", "Malibu Town", "Malibu Towers"],
  ["Gurgaon", "MG Road", "Suncity Platinum Towers"],
  ["Gurgaon", "Nirvana Country", "Unitech Fresco"],
  ["Gurgaon", "Nirvana Country", "The Close North"],
  ["Gurgaon", "Nirvana Country", "Unitech Escape"],
  ["Gurgaon", "Nirvana Country", "The Close South"],
  ["Gurgaon", "Nirvana Country", "Unitech Harmony"],
  ["Gurgaon", "Palam Vihar", "Bestech Park View Residency"],
  ["Gurgaon", "Palam Vihar", "Ansals Palam Vihar"],
  ["Gurgaon", "Palam Vihar", "Celebrity Homes"],
  ["Gurgaon", "Sector 1 Imt Manesar", "HSIIDC Sidco Shivalik Apartments"],
  ["Gurgaon", "Sector 1 Imt Manesar", "HSIIDC Sidco Aravali"],
  ["Gurgaon", "Sector 102", "Shapoorji Pallonji Joyville Gurugram"],
  ["Gurgaon", "Sector 102", "Adani M2K Oyster Grande"],
  ["Gurgaon", "Sector 102", "Emaar Imperial Gardens"],
  ["Gurgaon", "Sector 102", "Conscient Heritage Max"],
  ["Gurgaon", "Sector 102", "Emaar Gurgaon Greens"],
  ["Gurgaon", "Sector 102", "ROF Aalayas"],
  ["Gurgaon", "Sector 102", "Suncity Avenue 102"],
  ["Gurgaon", "Sector 102", "BPTP Amstoria"],
  ["Gurgaon", "Sector 102", "Adani Oyster Greens"],
  ["Gurgaon", "Sector 103", "Indiabulls Centrum Park"],
  ["Gurgaon", "Sector 103", "Signature Global Grand IVA"],
  ["Gurgaon", "Sector 103", "Satya The Hermitage"],
  ["Gurgaon", "Sector 103", "Ansal Housing Highland Park"],
  ["Gurgaon", "Sector 103", "Landmark The Residency"],
  ["Gurgaon", "Sector 104", "Hero Homes"],
  ["Gurgaon", "Sector 104", "Puri Emerald Bay"],
  ["Gurgaon", "Sector 104", "ATS Triumph"],
  ["Gurgaon", "Sector 104", "Godrej Summit"],
  ["Gurgaon", "Sector 104", "Zara Aavaas"],
  ["Gurgaon", "Sector 106", "Godrej Meridien"],
  ["Gurgaon", "Sector 106", "Paras Dews"],
  ["Gurgaon", "Sector 106", "Viridian The Plaza 106"],
  ["Gurgaon", "Sector 106", "Elan The Presidential"],
  ["Gurgaon", "Sector 107", "M3M Woodshire"],
  ["Gurgaon", "Sector 107", "Signature Global Solera"],
  ["Gurgaon", "Sector 107", "Signature Global Solera 2"],
  ["Gurgaon", "Sector 108", "Sobha City"],
  ["Gurgaon", "Sector 108", "Experion The Heartsong"],
  ["Gurgaon", "Sector 108", "Raheja Vedaanta"],
  ["Gurgaon", "Sector 108", "ROF Alante"],
  ["Gurgaon", "Sector 109", "ATS Tourmaline"],
  ["Gurgaon", "Sector 109", "ATS Kocoon"],
  ["Gurgaon", "Sector 109", "Chintels Serenity"],
  ["Gurgaon", "Sector 109", "Brisk Lumbini Terrace Homes"],
  ["Gurgaon", "Sector 109", "Raheja Atharva"],
  ["Gurgaon", "Sector 109", "SBTL Caladium"],
  ["Gurgaon", "Sector 109", "Raheja Shilas"],
  ["Gurgaon", "Sector 110", "Indiabulls Enigma"],
  ["Gurgaon", "Sector 110 A", "Mahindra Aura"],
  ["Gurgaon", "Sector 111", "Puri Diplomatic Greens"],
  ["Gurgaon", "Sector 111", "Tashee Capital Gateway"],
  ["Gurgaon", "Sector 111", "Kashish Manor One"],
  ["Gurgaon", "Sector 111", "Lotus Homz"],
  ["Gurgaon", "Sector 111", "M3M Crown"],
  ["Gurgaon", "Sector 112", "Experion Windchants"],
  ["Gurgaon", "Sector 112", "Tata Gurgaon Gateway"],
  ["Gurgaon", "Sector 112", "Zara Rossa"],
  ["Gurgaon", "Sector 112", "Pareena Om Apartments"],
  ["Gurgaon", "Sector 113", "La Vida by Tata Housing"],
  ["Gurgaon", "Sector 113", "M3M Capital"],
  ["Gurgaon", "Sector 113", "Smartworld One DXP"],
  ["Gurgaon", "Sector 113", "M3M Mansion"],
  ["Gurgaon", "Sector 15", "Maxworth Premier Urban"],
  ["Gurgaon", "Sector 1A IMT Manesar", "DLF Express Greens"],
  ["Gurgaon", "Sector 2", "Mittal Cosmos Executive Apartments"],
  ["Gurgaon", "Sector 22", "Ambience Creacions"],
  ["Gurgaon", "Sector 22", "Alpha Gurgaon One 22"],
  ["Gurgaon", "Sector 28", "Suncity Essel Towers"],
  ["Gurgaon", "Sector 28", "Silverglades The Ivy"],
  ["Gurgaon", "Sector 3", "Godrej Habitat"],
  ["Gurgaon", "Sector 30", "Unitech Uniworld City"],
  ["Gurgaon", "Sector 30", "Unitech The World Spa West"],
  ["Gurgaon", "Sector 31", "Raheja Atlantis"],
  ["Gurgaon", "Sector 33", "Unitech The Residences"],
  ["Gurgaon", "Sector 33", "JMD Gardens"],
  ["Gurgaon", "Sector 36 Sohna", "Signature Global Park 4"],
  ["Gurgaon", "Sector 36A", "Krisumi Waterfall Residences"],
  ["Gurgaon", "Sector 36A", "AVL 36 Gurgaon"],
  ["Gurgaon", "Sector 37C", "Imperia The Esfera"],
  ["Gurgaon", "Sector 37C", "ILD Greens"],
  ["Gurgaon", "Sector 37C", "Apex Our Homes"],
  ["Gurgaon", "Sector 37C", "ILD Grand"],
  ["Gurgaon", "Sector 37C", "Piedmont Taksila heights"],
  ["Gurgaon", "Sector 37C", "Corona Optus"],
  ["Gurgaon", "Sector 37C", "Ramprastha The View"],
  ["Gurgaon", "Sector 37D", "Signature Global the Millennia"],
  ["Gurgaon", "Sector 37D", "BPTP Terra"],
  ["Gurgaon", "Sector 37D", "Ramprastha The Edge Towers"],
  ["Gurgaon", "Sector 37D", "Signature Global The Millennia 2"],
  ["Gurgaon", "Sector 37D", "Signature Global City"],
  ["Gurgaon", "Sector 37D", "BPTP Spacio"],
  ["Gurgaon", "Sector 37D", "BPTP Park Generations"],
  ["Gurgaon", "Sector 37D", "BPTP Park Serene"],
  ["Gurgaon", "Sector 37D", "Ramprastha Primera"],
  ["Gurgaon", "Sector 37D", "Signature Global The Millennia 3"],
  ["Gurgaon", "Sector 37D", "Ramprastha The Atrium"],
  ["Gurgaon", "Sector 41", "Unitech The Palms"],
  ["Gurgaon", "Sector 41", "Unitech Ivory Towers"],
  ["Gurgaon", "Sector 42", "DLF The Magnolias"],
  ["Gurgaon", "Sector 42", "DLF The Camellias"],
  ["Gurgaon", "Sector 42", "DLF The Aralias"],
  ["Gurgaon", "Sector 42", "Central Park"],
  ["Gurgaon", "Sector 43", "Ansal Maple Heights"],
  ["Gurgaon", "Sector 43", "Bancourt Apartment"],
  ["Gurgaon", "Sector 43", "Tarika Apartments"],
  ["Gurgaon", "Sector 43", "Millenium Bajrang Society"],
  ["Gurgaon", "Sector 43", "AWHO Sujjan Vihar"],
  ["Gurgaon", "Sector 43", "HBH Galaxy Apartments"],
  ["Gurgaon", "Sector 43", "Sanskriti Apartments"],
  ["Gurgaon", "Sector 45", "Shree Ganesh Apartments"],
  ["Gurgaon", "Sector 45", "Jasminium Apartment"],
  ["Gurgaon", "Sector 47", "Unitech Uniworld Gardens 2"],
  ["Gurgaon", "Sector 47", "Unitech Uniworld Gardens"],
  ["Gurgaon", "Sector 47", "Bestech Park View Spa"],
  ["Gurgaon", "Sector 47", "IRWO Westend Towers"],
  ["Gurgaon", "Sector 48", "Central Park Resorts"],
  ["Gurgaon", "Sector 48", "Vipul Greens"],
  ["Gurgaon", "Sector 48", "Parsvnath Green Ville"],
  ["Gurgaon", "Sector 48", "Central Park 2 Bellevue"],
  ["Gurgaon", "Sector 48", "Bestech Park View City"],
  ["Gurgaon", "Sector 48", "Belaperla Central Park Resorts"],
  ["Gurgaon", "Sector 48", "Central Park The Room"],
  ["Gurgaon", "Sector 48", "Central Park Resort Belgravia Residences"],
  ["Gurgaon", "Sector 48", "Vipul World"],
  ["Gurgaon", "Sector 49", "Orchid Petals"],
  ["Gurgaon", "Sector 49", "Vatika City"],
  ["Gurgaon", "Sector 49", "Bestech Park View City 2"],
  ["Gurgaon", "Sector 49", "AWHO Sispal Vihar"],
  ["Gurgaon", "Sector 49", "Omaxe The Nile"],
  ["Gurgaon", "Sector 50", "Eros Wembley Estate"],
  ["Gurgaon", "Sector 50", "SS Hibiscus"],
  ["Gurgaon", "Sector 51", "Orchid Island"],
  ["Gurgaon", "Sector 51", "Citizen apartment"],
  ["Gurgaon", "Sector 52", "Ansal API Sushant Estate"],
  ["Gurgaon", "Sector 52", "Ardee City"],
  ["Gurgaon", "Sector 52", "New Greenwood Society"],
  ["Gurgaon", "Sector 52", "Friends Apartment"],
  ["Gurgaon", "Sector 52", "EMERALD GREEN"],
  ["Gurgaon", "Sector 53", "Tulip Monsella"],
  ["Gurgaon", "Sector 53", "Parsvnath Exotica"],
  ["Gurgaon", "Sector 53", "Vipul Belmonte"],
  ["Gurgaon", "Sector 53", "TDI Ourania"],
  ["Gurgaon", "Sector 54", "DLF Park Place"],
  ["Gurgaon", "Sector 54", "DLF The Crest"],
  ["Gurgaon", "Sector 54", "DLF The Belaire"],
  ["Gurgaon", "Sector 54", "Emaar The Palm Springs"],
  ["Gurgaon", "Sector 54", "Salcon The Verandas"],
  ["Gurgaon", "Sector 54", "La Lagune"],
  ["Gurgaon", "Sector 54", "DLF The Summit"],
  ["Gurgaon", "Sector 54", "Orchid Gardens"],
  ["Gurgaon", "Sector 54", "Suncity Heights"],
  ["Gurgaon", "Sector 55", "Oasis Apartment"],
  ["Gurgaon", "Sector 56", "Kendriya Vihar"],
  ["Gurgaon", "Sector 56", "CGHS HEWO Apartments"],
  ["Gurgaon", "Sector 56", "AWHO Devinder Vihar"],
  ["Gurgaon", "Sector 56", "Intelligentsia Apartment"],
  ["Gurgaon", "Sector 56", "Antriksh Royal Palm Apartments"],
  ["Gurgaon", "Sector 56", "Technocrat Society"],
  ["Gurgaon", "Sector 56", "Gail CGHS"],
  ["Gurgaon", "Sector 56", "Jalvayu Towers"],
  ["Gurgaon", "Sector 56", "Park View Apartment"],
  ["Gurgaon", "Sector 56", "Prerna Society"],
  ["Gurgaon", "Sector 56", "Alaknanda Apartments"],
  ["Gurgaon", "Sector 56", "Bhagwanti Apartment"],
  ["Gurgaon", "Sector 56", "Priyadarshini CHS"],
  ["Gurgaon", "Sector 56", "Gracious Tower"],
  ["Gurgaon", "Sector 56", "Suncity Sukriti"],
  ["Gurgaon", "Sector 56", "Suvidha Apartment"],
  ["Gurgaon", "Sector 56", "Madhur Jeevan Apartments"],
  ["Gurgaon", "Sector 57", "BPTP Freedom Park Life"],
  ["Gurgaon", "Sector 57", "Satya The Legend"],
  ["Gurgaon", "Sector 57", "IRWO Classic Apartments"],
  ["Gurgaon", "sector 58", "Ireo The Grand Arch"],
  ["Gurgaon", "Sector 59", "Conscient Elevate"],
  ["Gurgaon", "Sector 59", "Mahindra Luminare"],
  ["Gurgaon", "Sector 59", "Raisina Residency"],
  ["Gurgaon", "Sector 59", "Pyramid Midtown"],
  ["Gurgaon", "Sector 60", "Ireo Skyon"],
  ["Gurgaon", "Sector 60", "Adani Brahma Samsara"],
  ["Gurgaon", "Sector 61", "Smart World Orchard"],
  ["Gurgaon", "Sector 61", "Pioneer Park"],
  ["Gurgaon", "Sector 61", "Smart World Orchard Street"],
  ["Gurgaon", "Sector 61", "Suposhaa Smartworld Orchard"],
  ["Gurgaon", "Sector 62", "Emaar Digihomes"],
  ["Gurgaon", "Sector 62", "Pioneer Araya"],
  ["Gurgaon", "Sector 62", "Pioneer Urban Presidia"],
  ["Gurgaon", "Sector 62", "Conscient Heritage One"],
  ["Gurgaon", "Sector 62", "Pivotal Paradise"],
  ["Gurgaon", "Sector 63", "Adani Brahma Samsara Vilasa"],
  ["Gurgaon", "Sector 63", "Adani Samsara Avasa"],
  ["Gurgaon", "Sector 63A", "Signature Global Prime"],
  ["Gurgaon", "Sector 63A", "Signature Global City 63A"],
  ["Gurgaon", "Sector 63A", "Birla Navya"],
  ["Gurgaon", "Sector 63A", "Anant Raj"],
  ["Gurgaon", "Sector 63A", "Laburnum Victory Floors"],
  ["Gurgaon", "Sector 63A", "TARC Ishva"],
  ["Gurgaon", "Sector 65", "M3M Heights"],
  ["Gurgaon", "Sector 65", "M3M Golfestate"],
  ["Gurgaon", "Sector 65", "Trump Tower"],
  ["Gurgaon", "Sector 65", "Emaar MGF Emerald Floors Premier"],
  ["Gurgaon", "Sector 65", "Emaar MGF Emerald Estate"],
  ["Gurgaon", "Sector 65", "M3M Skycity"],
  ["Gurgaon", "Sector 65", "Emaar Emerald Hills"],
  ["Gurgaon", "Sector 65", "M3M Latitude"],
  ["Gurgaon", "Sector 65", "M3M St Andrews"],
  ["Gurgaon", "Sector 66", "Emaar MGF The Palm Drive"],
  ["Gurgaon", "Sector 66", "Emaar Mgf Palm Terraces Select"],
  ["Gurgaon", "Sector 66", "BPTP Park Prime"],
  ["Gurgaon", "Sector 66", "Ireo Uptown"],
  ["Gurgaon", "Sector 66", "BPTP Mansions Park Prime"],
  ["Gurgaon", "Sector 66", "Emaar MGF The Enclave"],
  ["Gurgaon", "Sector 67", "M3M Merlin"],
  ["Gurgaon", "Sector 67", "Bestech Park View Spa Next"],
  ["Gurgaon", "Sector 67", "Ireo Victory Valley"],
  ["Gurgaon", "Sector 67", "Shree Vardhman Mantra"],
  ["Gurgaon", "Sector 67", "Ansal API Esencia"],
  ["Gurgaon", "Sector 67A", "Ireo The Corridors"],
  ["Gurgaon", "Sector 67A", "Pyramid Urban"],
  ["Gurgaon", "Sector 68", "Pareena Mi Casa"],
  ["Gurgaon", "Sector 68", "M3M The Marina"],
  ["Gurgaon", "Sector 68", "M3M Sierra 68"],
  ["Gurgaon", "Sector 68", "M3M Flora"],
  ["Gurgaon", "Sector 68", "M3M Natura"],
  ["Gurgaon", "Sector 68", "Supertech Hues"],
  ["Gurgaon", "Sector 69", "Tulip Yellow"],
  ["Gurgaon", "Sector 69", "Tulip Violet"],
  ["Gurgaon", "Sector 69", "Tulip Purple"],
  ["Gurgaon", "Sector 69", "Tulip White"],
  ["Gurgaon", "Sector 69", "Tulip Lemon"],
  ["Gurgaon", "Sector 69", "Tulip Leaf"],
  ["Gurgaon", "Sector 70", "Shree Vardhman Victoria"],
  ["Gurgaon", "Sector 70", "Tulip Orange"],
  ["Gurgaon", "Sector 70", "GPL Eden Heights"],
  ["Gurgaon", "Sector 70", "Tulip Ivory"],
  ["Gurgaon", "Sector 70", "Tulip Crimson"],
  ["Gurgaon", "Sector 70", "Pyramid Altia"],
  ["Gurgaon", "Sector 70", "Unitech Vistas"],
  ["Gurgaon", "Sector 70A", "AIPL The Peaceful Homes"],
  ["Gurgaon", "Sector 70A", "Paras Irene"],
  ["Gurgaon", "Sector 70A", "Pyramid Fusion Homes"],
  ["Gurgaon", "Sector 70A", "Pyramid Urban Homes"],
  ["Gurgaon", "Sector 70A", "AIPL Zen Residences"],
  ["Gurgaon", "Sector 70A", "M3M Escala"],
  ["Gurgaon", "Sector 70A", "BPTP Astaire Gardens"],
  ["Gurgaon", "Sector 70A", "Capital Residences 360"],
  ["Gurgaon", "Sector 70A", "BPTP Pedestal"],
  ["Gurgaon", "Sector 71", "CHD Avenue 71"],
  ["Gurgaon", "Sector 71", "Signature Andour Heights"],
  ["Gurgaon", "Sector 71", "Trehan Luxury Floors 71"],
  ["Gurgaon", "Sector 72", "Tata Primanti"],
  ["Gurgaon", "Sector 72", "Spaze Privy"],
  ["Gurgaon", "Sector 73", "DLF Alameda"],
  ["Gurgaon", "Sector 74", "M3M Skywalk"],
  ["Gurgaon", "Sector 76", "Suncity Avenue 76"],
  ["Gurgaon", "Sector 76", "Pyramid Pride"],
  ["Gurgaon", "Sector 77", "Emaar MGF Palm Hills"],
  ["Gurgaon", "Sector 77", "Umang Winter Hills"],
  ["Gurgaon", "Sector 77", "Emaar Palm Heights"],
  ["Gurgaon", "Sector 77", "DLF Privana South"],
  ["Gurgaon", "Sector 78", "Umang Monsoon Breeze"],
  ["Gurgaon", "Sector 79", "Bestech Altura"],
  ["Gurgaon", "Sector 79", "Mapsko Mount Ville"],
  ["Gurgaon", "Sector 79", "Signature Global Golf Greens"],
  ["Gurgaon", "Sector 79", "Godrej Aria"],
  ["Gurgaon", "Sector 79", "Godrej 101"],
  ["Gurgaon", "Sector 79", "M3M Antalya Hills"],
  ["Gurgaon", "Sector 79", "Supertech Araville"],
  ["Gurgaon", "Sector 79", "M3M Golf Hills"],
  ["Gurgaon", "Sector 80", "Godrej Frontier"],
  ["Gurgaon", "Sector 81", "DLF The Ultima"],
  ["Gurgaon", "Sector 81", "Bestech Park View Grand Spa"],
  ["Gurgaon", "Sector 81", "Bestech Park View Ananda"],
  ["Gurgaon", "Sector 81", "Vipul Lavanya"],
  ["Gurgaon", "Sector 81", "Signature Global Synera"],
  ["Gurgaon", "Sector 81", "Signature Global City 81"],
  ["Gurgaon", "Sector 81", "Landmark The Homes 81"],
  ["Gurgaon", "Sector 82", "Vatika The Seven Lamps"],
  ["Gurgaon", "Sector 82", "Mapsko Casa Bella"],
  ["Gurgaon", "Sector 82", "Mapsko Royale Ville"],
  ["Gurgaon", "Sector 82A", "DLF The Primus"],
  ["Gurgaon", "Sector 82A", "Vatika Sovereign Next"],
  ["Gurgaon", "Sector 83", "Emaar Palm Gardens"],
  ["Gurgaon", "Sector 83", "Vatika Gurgaon 21"],
  ["Gurgaon", "Sector 83", "Vatika Lifestyle Homes"],
  ["Gurgaon", "Sector 83", "Mapsko Paradise"],
  ["Gurgaon", "Sector 83", "Vatika City Homes"],
  ["Gurgaon", "Sector 83", "Vatika Emilia Floors"],
  ["Gurgaon", "Sector 83", "SS Cendana Reserve Collection"],
  ["Gurgaon", "Sector 84", "Antriksh Heights"],
  ["Gurgaon", "Sector 84", "SS The Coralwood"],
  ["Gurgaon", "Sector 84", "Spaze Privy AT4"],
  ["Gurgaon", "Sector 84", "Alpha Corp GurgaonOne 84"],
  ["Gurgaon", "Sector 84", "Pivotal Devaan"],
  ["Gurgaon", "Sector 84", "SS Linden Floors"],
  ["Gurgaon", "Sector 84", "Spaze Kalistaa"],
  ["Gurgaon", "Sector 84", "SS Almeria"],
  ["Gurgaon", "Sector 85", "Godrej Air"],
  ["Gurgaon", "Sector 85", "SS The Leaf"],
  ["Gurgaon", "Sector 85", "Orris Carnation Residency"],
  ["Gurgaon", "Sector 85", "Pyramid Heights"],
  ["Gurgaon", "Sector 85", "Orris Aster Court"],
  ["Gurgaon", "Sector 85", "Orris Aster Court Premier"],
  ["Gurgaon", "Sector 86", "DLF The Skycourt"],
  ["Gurgaon", "Sector 86", "DLF New Town Heights 2"],
  ["Gurgaon", "Sector 86", "Pyramid Elite"],
  ["Gurgaon", "Sector 86", "Pyramid Urban Homes 2"],
  ["Gurgaon", "Sector 86", "Microtek Greenburg"],
  ["Gurgaon", "Sector 86", "Ansal Heights 86"],
  ["Gurgaon", "Sector 88A", "County The Center Court"],
  ["Gurgaon", "Sector 88A", "Adani Aangan"],
  ["Gurgaon", "Sector 88A", "Godrej Oasis"],
  ["Gurgaon", "Sector 88A", "Godrej Icon"],
  ["Gurgaon", "Sector 89", "Smart World Gems"],
  ["Gurgaon", "Sector 89", "M3M Soulitude"],
  ["Gurgaon", "Sector 89", "Greenopolis"],
  ["Gurgaon", "Sector 89", "Signature Global Proxima"],
  ["Gurgaon", "Sector 89", "Tulip Petals"],
  ["Gurgaon", "Sector 89", "Ace Palm Floors"],
  ["Gurgaon", "Sector 89 A", "Vatika Seven Elements"],
  ["Gurgaon", "Sector 89 A", "ATS Marigold"],
  ["Gurgaon", "Sector 90", "DLF New Town Heights 1"],
  ["Gurgaon", "Sector 90", "DLF Regal Gardens"],
  ["Gurgaon", "Sector 90", "Green Court"],
  ["Gurgaon", "Sector 90", "Shree Vardhman Flora"],
  ["Gurgaon", "Sector 91", "DLF New Town Heights"],
  ["Gurgaon", "Sector 91", "TARC Maceo"],
  ["Gurgaon", "Sector 92", "Sare Homes"],
  ["Gurgaon", "Sector 92", "Bestech Park View Sanskruti"],
  ["Gurgaon", "Sector 92", "GLS Avenue 51"],
  ["Gurgaon", "Sector 92", "Raheja Navodaya"],
  ["Gurgaon", "Sector 92", "ROF Amaltas"],
  ["Gurgaon", "Sector 92", "Signature Global City 92"],
  ["Gurgaon", "Sector 92", "Sare Crescent Parc"],
  ["Gurgaon", "Sector 92", "Raheja Sampada"],
  ["Gurgaon", "Sector 92", "Ansal Heights"],
  ["Gurgaon", "Sector 92", "Sare Petioles"],
  ["Gurgaon", "Sector 92", "DLF Garden City Floors"],
  ["Gurgaon", "Sector 92", "GLS South Avenue"],
  ["Gurgaon", "Sector 92", "Altura at DXP 92"],
  ["Gurgaon", "Sector 92", "Sare Crescent Parc Royal Greens Phase 1"],
  ["Gurgaon", "Sector 93", "Signature Global Orchard Avenue 2"],
  ["Gurgaon", "Sector 93", "MRG The Balcony"],
  ["Gurgaon", "Sector 93", "Spaze Privvy The Address"],
  ["Gurgaon", "Sector 93", "Signature Global Orchard Avenue"],
  ["Gurgaon", "Sector 93", "DLF Gardencity Enclave"],
  ["Gurgaon", "Sector 93", "Ashiana Amarah"],
  ["Gurgaon", "Sector 95", "ROF Ananda"],
  ["Gurgaon", "Sector 95", "Ramsons Kshitij"],
  ["Gurgaon", "Sector 95", "AWHO Shanti Vihar"],
  ["Gurgaon", "Sector 95", "Sidhartha NCR One Phase 1"],
  ["Gurgaon", "Sector 95", "Sidhartha NCR Greens"],
  ["Gurgaon", "Sector 95A", "Signature The Roselia"],
  ["Gurgaon", "Sector 99", "Vatika Sovereign Park"],
  ["Gurgaon", "Sector 99", "Assotech Blith"],
  ["Gurgaon", "Sector 99", "Pareena Express Heights"],
  ["Gurgaon", "Sector 99", "Cosmos Express 99"],
  ["Gurgaon", "Sector 99", "Lotus Elise"],
  ["Gurgaon", "Sector 99", "Pivotal Riddhi Siddhi"],
  ["Gurgaon", "Sector 99A", "Pareena Coban Residences"],
  ["Gurgaon", "Sector 99A", "Pareena Laxmi Apartments"],
  ["Gurgaon", "Sector 99A", "Conscient Habitat"],
  ["Gurgaon", "Sector-2 Sohna", "Ashiana Mulberry Blossom"],
  ["Gurgaon", "Sector-33 Sohna", "Central Park Flower Valley Aqua Front Towers"],
  ["Gurgaon", "Sector-33 Sohna", "Godrej Nature Plus"],
  ["Gurgaon", "Sector-33 Sohna", "Central Park Flower Valley"],
  ["Gurgaon", "Sector-33 Sohna", "Central Park Flower Valley Flamingo Floors"],
  ["Gurgaon", "Sector-33 Sohna", "Central Park Flower Valley Cerise Floors"],
  ["Gurgaon", "Sector-33 Sohna", "Godrej Nature Plus Serenity"],
  ["Gurgaon", "Sohna", "Silverglades The Melia"],
  ["Gurgaon", "Sohna", "Signature Global Park"],
  ["Gurgaon", "Sohna", "Ashiana Anmol"],
  ["Gurgaon", "Sohna", "GLS Arawali Homes"],
  ["Gurgaon", "Sohna", "Breez Global Heights"],
  ["Gurgaon", "Sohna", "Signature The Serenas"],
  ["Gurgaon", "Sohna", "Eldeco Accolade"],
  ["Gurgaon", "Sohna", "HCBS Sports Ville"],
  ["Gurgaon", "Sohna", "Ashiana Mulberry"],
  ["Gurgaon", "Sohna", "MVN Athens"],
  ["Gurgaon", "Sohna", "Trisara Our Homes 3"],
  ["Gurgaon", "Sohna", "Breez Global Hill View"],
  ["Gurgaon", "Sohna", "Eldeco Acclaim"],
  ["Gurgaon", "Sohna", "Central Park Flower Valley The Room"],
  ["Gurgaon", "Suncity", "Vipul Orchid Gardens"],
  ["Gurgaon", "Sushant Lok Phase 1", "Ansal Sushant Apartments"],
  ["Gurgaon", "Sushant Lok Phase 1", "Sushant Lok 1 Builder Floors"],
  ["Gurgaon", "Sushant Lok Phase 1", "Ansal Maple Crescent"],
  ["Gurgaon", "Sushant Lok Phase 3", "Ansal Harmony Homes"],
  ["Gurgaon", "Valley View Estate", "Tch Garden Residency"],

  // ── NOIDA ──
  ["Noida", "Alpha 1", "Spacetech Edana"],
  ["Noida", "Alpha 2", "Parsvnath Edens"],
  ["Noida", "Alpha 2", "Assotech Golf Vista Apartments"],
  ["Noida", "Arun Vihar", "Army Flats"],
  ["Noida", "Bela Khurd", "Presidency Heights Presithum"],
  ["Noida", "Beta 2", "AVJ Homes"],
  ["Noida", "Devla", "ultima allure"],
  ["Noida", "Ecotech 3", "Wow Monk"],
  ["Noida", "Eta 2", "Migsun Twinz"],
  ["Noida", "Eta 2", "Migsun Vilaasa"],
  ["Noida", "Eta 2", "SKA Metro Ville"],
  ["Noida", "Fatehpur", "Mahagun Manor"],
  ["Noida", "Gurjinder Vihar", "Twin Towers AWHO"],
  ["Noida", "Jalpura", "Ambesten Twin Chalet"],
  ["Noida", "Jalpura", "Trinity high street"],
  ["Noida", "Jaypee Greens", "Jaypee Greens Star Court"],
  ["Noida", "Jaypee Greens", "Jaypee Greens Moon Court"],
  ["Noida", "Jaypee Greens", "Jaypee Greens Crescent Court"],
  ["Noida", "Jaypee Greens", "Jaypee Greens The Sun Court"],
  ["Noida", "Jaypee Greens", "Jaypee The Castille"],
  ["Noida", "Jaypee Greens", "jaypee greens sea court"],
  ["Noida", "Jaypee Greens", "Jaypee Greens Spa Court"],
  ["Noida", "Knowledge Park 5", "Casa View Apartment 4"],
  ["Noida", "locality", "society"],
  ["Noida", "Noida Extension", "Gaur 16th Avenue"],
  ["Noida", "Noida Extension", "Gaur 12th Avenue"],
  ["Noida", "Noida Extension", "Amrapali Dream Valley High Life 2"],
  ["Noida", "Noida Extension", "Exotica Dreamville"],
  ["Noida", "Noida Extension", "Galaxy North Avenue 2"],
  ["Noida", "Noida Extension", "French Apartments"],
  ["Noida", "Noida Extension", "Supertech Ecovillage 3"],
  ["Noida", "Noida Extension", "Galaxy Vega"],
  ["Noida", "Noida Extension", "Stellar One"],
  ["Noida", "Noida Extension", "Town Park White Orchid"],
  ["Noida", "Noida Extension", "Amrapali Tropical Garden"],
  ["Noida", "Noida Extension", "Gaur City 10Th Avenue"],
  ["Noida", "Noida Extension", "Geotech Pristine Avenue"],
  ["Noida", "Noida Extension", "(blank)"],
  ["Noida", "Noida Extension", "Sky Gardens"],
  ["Noida", "Noida Extension", "Twin Celestial by Ambesten Homes"],
  ["Noida", "Noida Extension", "Vihaan Vista"],
  ["Noida", "Noida Extension", "Gayatri Life"],
  ["Noida", "Noida Extension", "Aig Park Avenue"],
  ["Noida", "Noida Extension", "Amrapali O2 Valley"],
  ["Noida", "NRI City", "SDS NRI Residency"],
  ["Noida", "NRI City", "Omaxe NRI City"],
  ["Noida", "NRI City", "Omaxe Putting Greens"],
  ["Noida", "Sector 1 West", "ACE Divino"],
  ["Noida", "Sector 1 West", "Ace City"],
  ["Noida", "Sector 1 West", "ATS Rhapsody"],
  ["Noida", "Sector 1 West", "Stellar Jeevan"],
  ["Noida", "Sector 1 West", "Arihant Arden"],
  ["Noida", "Sector 1 West", "CRC Sublimis"],
  ["Noida", "Sector 1 West", "Hawelia Valencia Homes"],
  ["Noida", "Sector 1 West", "Trident Embassy"],
  ["Noida", "Sector 1 West", "Paramount Emotions"],
  ["Noida", "Sector 1 West", "Apex Aura"],
  ["Noida", "Sector 1 West", "NCR Monarch and Crown"],
  ["Noida", "Sector 1 West", "Arihant Ambar"],
  ["Noida", "Sector 1 West", "Trident Embassy Reso"],
  ["Noida", "Sector 1 West", "Capital Athena"],
  ["Noida", "Sector 1 West", "Supertech Ecovillage 1"],
  ["Noida", "Sector 1 West", "AIGIN Royal"],
  ["Noida", "Sector 1 West", "Apex Golf Avenue"],
  ["Noida", "Sector 1 West", "Panchsheel Hynish"],
  ["Noida", "Sector 1 West", "Irish Pearls"],
  ["Noida", "Sector 1 West", "The Valley"],
  ["Noida", "Sector 1 West", "Apex Alphabet"],
  ["Noida", "Sector 1 West", "Lucky Krishna Elite Homes"],
  ["Noida", "Sector 1 West", "BNH Casa View Orchid Aurum"],
  ["Noida", "Sector 1 West", "Sportshome by Dev Sai Group"],
  ["Noida", "Sector 1 West", "SRPL Flora Heritage"],
  ["Noida", "Sector 1 West", "Rudra Palace Heights"],
  ["Noida", "Sector 1 West", "Orchid Residency"],
  ["Noida", "Sector 1 West", "Vihaan Heritage"],
  ["Noida", "Sector 1 West", "Vihaan Greens"],
  ["Noida", "Sector 1 West", "Vrinda Heritage Skyward"],
  ["Noida", "Sector 1 West", "Devika Gold Homz"],
  ["Noida", "Sector 1 West", "Rajhans Residency"],
  ["Noida", "Sector 1 West", "Vihaan Wisteria"],
  ["Noida", "Sector 1 West", "ATS Destinaire"],
  ["Noida", "Sector 1 West", "SAM RISE INN"],
  ["Noida", "Sector 1 West", "Clover Spring Homes"],
  ["Noida", "Sector 1 West", "Lucky The Palm Valley"],
  ["Noida", "Sector 1 West", "Vihaan Wardenia"],
  ["Noida", "Sector 1 West", "Future Estate by FW Group"],
  ["Noida", "Sector 1 West", "Rise Resort Residences"],
  ["Noida", "Sector 1 West", "Express Astra"],
  ["Noida", "Sector 1 West", "orchid aurum"],
  ["Noida", "Sector 1 West", "Trinity Grand"],
  ["Noida", "Sector 10 West", "HomeKraft Happy Trails"],
  ["Noida", "Sector 10 West", "Coco County"],
  ["Noida", "Sector 10 West", "Arihant Abode"],
  ["Noida", "Sector 10 West", "Amaatra Homes"],
  ["Noida", "Sector 10 West", "Mahagun Mantraa 2"],
  ["Noida", "Sector 10 West", "Sikka Kaamya Greens"],
  ["Noida", "Sector 10 West", "Mahagun Mantraa 1"],
  ["Noida", "Sector 10 West", "Greater Noida Authority Apartment"],
  ["Noida", "Sector 100", "3C Lotus Boulevard"],
  ["Noida", "Sector 100", "3C Lotus Boulevard Espacia"],
  ["Noida", "Sector 104", "ATS One Hamlet"],
  ["Noida", "Sector 104", "golden residency"],
  ["Noida", "Sector 104", "Chauhan Apartments"],
  ["Noida", "Sector 107", "Amrapali HeartBeat City"],
  ["Noida", "Sector 107", "County 107"],
  ["Noida", "Sector 107", "Great Value Sharanam"],
  ["Noida", "Sector 107", "3C Lotus 300"],
  ["Noida", "Sector 107", "Sunworld Vanalika"],
  ["Noida", "Sector 107", "Prateek Edifice"],
  ["Noida", "Sector 107", "Arena The Ultima Heights"],
  ["Noida", "Sector 107", "Great Value Anandam"],
  ["Noida", "Sector 108", "Parx Laureate"],
  ["Noida", "Sector 108", "Elixir Divine Meadows"],
  ["Noida", "Sector 110", "3C Lotus Panache"],
  ["Noida", "Sector 110", "Royal Residency"],
  ["Noida", "Sector 115", "Ivory County"],
  ["Noida", "Sector 118", "Supertech The Romano"],
  ["Noida", "Sector 118", "Ajnara Ambrosia"],
  ["Noida", "Sector 119", "Amrapali Platinum"],
  ["Noida", "Sector 119", "Uninati The Aranya"],
  ["Noida", "Sector 119", "Gaur Grandeur"],
  ["Noida", "Sector 119", "Eldeco Aamantran"],
  ["Noida", "Sector 119", "Eldeco Magnolia Park"],
  ["Noida", "Sector 119", "Eldeco Inspire"],
  ["Noida", "Sector 120", "Amrapali Zodiac"],
  ["Noida", "Sector 120", "Prateek Laurel"],
  ["Noida", "Sector 120", "RG Residency"],
  ["Noida", "Sector 121", "ABA Cleo County"],
  ["Noida", "Sector 121", "Homes 121"],
  ["Noida", "Sector 121", "ABA Cleo Gold"],
  ["Noida", "Sector 128", "Jaypee Greens Kalypso Court"],
  ["Noida", "Sector 128", "Jaypee Greens Knights Court"],
  ["Noida", "Sector 128", "Kalpataru Vista"],
  ["Noida", "Sector 128", "Jaypee Greens The Pavilion Court"],
  ["Noida", "Sector 128", "Jaypee Greens Imperial Court"],
  ["Noida", "Sector 128", "Jaypee Greens Pavilion Heights"],
  ["Noida", "Sector 128", "Jaypee Wish Town"],
  ["Noida", "Sector 128", "Jaypee Augusta Town Homes"],
  ["Noida", "Sector 129", "Jaypee Greens Wish Town Klassic"],
  ["Noida", "Sector 131", "Jaypee Greens Kensington Boulevard"],
  ["Noida", "Sector 133", "Jaypee Greens Kensington Park Apartments"],
  ["Noida", "Sector 133", "Jaypee Greens Garden Isles"],
  ["Noida", "Sector 134", "Jaypee Greens Kosmos"],
  ["Noida", "Sector 134", "Jaypee Greens Klassic"],
  ["Noida", "Sector 134", "Jaypee Klassic Shaurya"],
  ["Noida", "Sector 134", "Jaypee Greens Klassic Heights"],
  ["Noida", "Sector 134", "Jaypee Greens Klassic A"],
  ["Noida", "Sector 134", "Jaypee Wish Point"],
  ["Noida", "Sector 135", "Today Ridge Residency"],
  ["Noida", "Sector 137", "Paras Tierea"],
  ["Noida", "Sector 137", "Supertech Ecociti"],
  ["Noida", "Sector 137", "Purvanchal Royal Park"],
  ["Noida", "Sector 137", "Gulshan Vivante"],
  ["Noida", "Sector 137", "Paramount Floraville"],
  ["Noida", "Sector 137", "Logix Blossom County"],
  ["Noida", "Sector 137", "Ajnara Daffodil"],
  ["Noida", "Sector 137", "Exotica Fresco"],
  ["Noida", "Sector 143", "Gulshan Ikebana"],
  ["Noida", "Sector 143", "Logix Blossom Greens"],
  ["Noida", "Sector 143", "Sikka Kaamna Greens"],
  ["Noida", "Sector 143", "Logix Blossom Zest"],
  ["Noida", "Sector 143B", "SKA Orion"],
  ["Noida", "Sector 143B", "Rani Aakriti Shantiniketan"],
  ["Noida", "Sector 143B", "Sikka Karnam Greens"],
  ["Noida", "Sector 144", "Gulshan Botnia"],
  ["Noida", "Sector 144", "Gulshan Dynasty"],
  ["Noida", "Sector 146", "Godrej Tropical Isle"],
  ["Noida", "Sector 150", "ACE Parkway"],
  ["Noida", "Sector 150", "ATS Pious Hideaways"],
  ["Noida", "Sector 150", "Eldeco Live By The Greens"],
  ["Noida", "Sector 150", "ATS Le Grandiose"],
  ["Noida", "Sector 150", "Samridhi Luxuriya Avenue"],
  ["Noida", "Sector 150", "ATS Pristine"],
  ["Noida", "Sector 150", "Eureka Park By Tata Value Homes"],
  ["Noida", "Sector 150", "ACE Golfshire"],
  ["Noida", "Sector 150", "Godrej Nest"],
  ["Noida", "Sector 150", "Godrej Palm Retreat"],
  ["Noida", "Sector 150", "TATA Value Homes"],
  ["Noida", "Sector 150", "Mahagun Meadow"],
  ["Noida", "Sector 150", "Antriksh Golf City"],
  ["Noida", "Sector 150", "Godrej Nurture"],
  ["Noida", "Sector 150", "Antriksh Grand View"],
  ["Noida", "Sector 150", "Max Antara Noida"],
  ["Noida", "Sector 150", "Prateek Canary"],
  ["Noida", "Sector 151", "Jaypee Aman"],
  ["Noida", "Sector 152", "Ace Starlit"],
  ["Noida", "Sector 152", "ATS Picturesque Reprieves"],
  ["Noida", "Sector 16", "Panchsheel Greens 2"],
  ["Noida", "Sector 16", "Gulshan Bellina"],
  ["Noida", "Sector 16", "Nirala Aspire"],
  ["Noida", "Sector 16", "SKA Divya Towers"],
  ["Noida", "Sector 16", "Ratan Pearls"],
  ["Noida", "Sector 16", "Victoryone Amara"],
  ["Noida", "Sector 16", "Emenox La Solara"],
  ["Noida", "Sector 16", "Radhey Krishna Casa Greens 1"],
  ["Noida", "Sector 16", "B S Vaibhav Heritage Height"],
  ["Noida", "Sector 16", "Radicon Vedantam"],
  ["Noida", "Sector 16", "Aarcity Regency Park"],
  ["Noida", "Sector 16", "Nirala Aspire Low Rise Phase 4"],
  ["Noida", "Sector 16", "Royal Court"],
  ["Noida", "Sector 168", "The Golden Palm"],
  ["Noida", "Sector 168", "Paras Seasons"],
  ["Noida", "Sector 168", "Sunworld Arista"],
  ["Noida", "Sector 168", "3C Lotus Zing"],
  ["Noida", "Sector 168", "Urbtech Xaviers"],
  ["Noida", "Sector 16B", "Shri Radha Sky Gardens"],
  ["Noida", "Sector 16B", "Ajnara Homes"],
  ["Noida", "Sector 16B", "Ajnara Le Garden"],
  ["Noida", "Sector 16B", "Supertech Ecovillage 2"],
  ["Noida", "Sector 16B", "Panchsheel Greens"],
  ["Noida", "Sector 16B", "Amrapali Dream Valley"],
  ["Noida", "Sector 16B", "SKA Greenarch"],
  ["Noida", "Sector 16B", "Shri Radha Aqua Gardens"],
  ["Noida", "Sector 16B", "RG Luxury Homes"],
  ["Noida", "Sector 16B", "Anthem French Apartments"],
  ["Noida", "Sector 16B", "Strategic Royal Court"],
  ["Noida", "Sector 16B", "Supertech Oxford Square"],
  ["Noida", "Sector 16C", "Gaur City 2 14th Avenue"],
  ["Noida", "Sector 16C", "Mahagun Mywoods Phase 1"],
  ["Noida", "Sector 16C", "Gaur City 2 11th Avenue"],
  ["Noida", "Sector 16C", "Sam Palm Olympia"],
  ["Noida", "Sector 16C", "Mahagun Mywoods Phase 2"],
  ["Noida", "Sector 16C", "Gaur City 2"],
  ["Noida", "Sector 16C", "Divyansh Flora"],
  ["Noida", "Sector 16C", "Galaxy Royale"],
  ["Noida", "Sector 16C", "AFOWO Raksha Addela"],
  ["Noida", "Sector 16C", "Sanskriti Vihar 10th Avenue"],
  ["Noida", "Sector 16C", "Casa Woodstock"],
  ["Noida", "Sector 16C", "Solitaire VVIP Homes"],
  ["Noida", "Sector 16C", "Mahagun Mywoods Phase 3"],
  ["Noida", "Sector 16C", "Wall Rock Aishwaryam"],
  ["Noida", "Sector 2", "Eros Sampoornam"],
  ["Noida", "Sector 2", "Nirala Greenshire"],
  ["Noida", "Sector 2", "Eros Sampoornam 2"],
  ["Noida", "Sector 21", "Air Force Naval Housing Board"],
  ["Noida", "Sector 22D Yamuna Expressway", "Oasis GrandStand"],
  ["Noida", "Sector 22D Yamuna Expressway", "YEIDA RPS 02"],
  ["Noida", "Sector 25", "RWA Jalvayu Vihar"],
  ["Noida", "Sector 27", "Godrej Golf Links The Suites"],
  ["Noida", "Sector 27", "Godrej Golf Link Park Lane"],
  ["Noida", "Sector 27", "Godrej Golf Links Windsor"],
  ["Noida", "Sector 27", "The Hemisphere"],
  ["Noida", "Sector 28", "Yamuna Enclave"],
  ["Noida", "Sector 28", "Army Welfare"],
  ["Noida", "Sector 28", "Arun Vihar"],
  ["Noida", "Sector 29", "India Gate Apartment"],
  ["Noida", "Sector 31", "Parsvnath Panorama"],
  ["Noida", "Sector 32", "Wave Amore"],
  ["Noida", "Sector 34", "Supertech 34 Pavilion"],
  ["Noida", "Sector 34", "RWA Nar Vihar"],
  ["Noida", "Sector 37", "Arun Vihar Noida"],
  ["Noida", "Sector 37", "Army Welfare Housing"],
  ["Noida", "Sector 4", "Amrapali Golf Homes"],
  ["Noida", "Sector 4", "Gaur City 7th Avenue"],
  ["Noida", "Sector 4", "Amrapali Centurian Park Terrace Homes"],
  ["Noida", "Sector 4", "ATS Nobility"],
  ["Noida", "Sector 4", "Gaur City 1st Avenue"],
  ["Noida", "Sector 4", "Saya Zion"],
  ["Noida", "Sector 4", "Gaur City 5th Avenue"],
  ["Noida", "Sector 4", "Aastha Greens"],
  ["Noida", "Sector 4", "Gaur City 6th Avenue"],
  ["Noida", "Sector 4", "Aims Green Avenue"],
  ["Noida", "Sector 4", "Galaxy North Avenue"],
  ["Noida", "Sector 4", "Gaur City"],
  ["Noida", "Sector 4", "Gaur City 4th Avenue"],
  ["Noida", "Sector 43", "Godrej Woods"],
  ["Noida", "Sector 44", "Pearls Gateway Towers"],
  ["Noida", "Sector 44", "Defence Enclave Sector 44 Noida"],
  ["Noida", "Sector 44", "Assotech Celeste Towers"],
  ["Noida", "Sector 45", "Amrapali Sapphire"],
  ["Noida", "Sector 45", "Prateek Stylome"],
  ["Noida", "Sector 46", "Gardenia Glory"],
  ["Noida", "Sector 48", "Eldeco Ananda"],
  ["Noida", "Sector 49", "Sector 49 RWA"],
  ["Noida", "Sector 50", "Ambience Tiverton"],
  ["Noida", "Sector 50", "Amrapali Eden Park"],
  ["Noida", "Sector 50", "Mahagun Morpheus"],
  ["Noida", "Sector 50", "Antriksh Greens"],
  ["Noida", "Sector 50", "Stellar Kings Court"],
  ["Noida", "Sector 50", "Mahagun Maestro"],
  ["Noida", "Sector 50", "Purvanchal Kailash Dham SAS"],
  ["Noida", "Sector 50", "ATS Greens 2"],
  ["Noida", "Sector 50", "TGB Meghdutam"],
  ["Noida", "Sector 50", "Alok Vihar 1"],
  ["Noida", "Sector 50", "Assotech Windsor Greens"],
  ["Noida", "Sector 50", "ATS Greens 1"],
  ["Noida", "Sector 50", "Mahagun Maple"],
  ["Noida", "Sector 50", "Omaxe Twin Towers"],
  ["Noida", "Sector 50", "Alok Vihar 2"],
  ["Noida", "Sector 50", "Shubhkamna Appartment"],
  ["Noida", "Sector 51", "Kendriya Vihar"],
  ["Noida", "Sector 52", "Antriksh Nature"],
  ["Noida", "Sector 52", "Arawali Apartment"],
  ["Noida", "Sector 61", "Royale Garden Estate"],
  ["Noida", "Sector 61", "Mapsko Krishna Apra Residency"],
  ["Noida", "Sector 61", "Prateek Fedora"],
  ["Noida", "Sector 61", "Gardenia Grace"],
  ["Noida", "Sector 61", "Shatabdi Vihar"],
  ["Noida", "Sector 61", "Indraprastha Villa"],
  ["Noida", "Sector 62", "Varun Apartments"],
  ["Noida", "Sector 62", "Telecom City"],
  ["Noida", "Sector 62", "Purvanchal PMO Apartments"],
  ["Noida", "Sector 62", "Gail Apartments"],
  ["Noida", "Sector 62", "Vinayak Apartment"],
  ["Noida", "Sector 70", "Pan Oasis"],
  ["Noida", "Sector 73", "Elite homes"],
  ["Noida", "Sector 73", "ABCZ East Avenue"],
  ["Noida", "Sector 73", "Divine Home"],
  ["Noida", "Sector 74", "Supertech Cape Town"],
  ["Noida", "Sector 74", "Grand Ajnara Heritage"],
  ["Noida", "Sector 75", "Ivy County"],
  ["Noida", "Sector 75", "Golf City"],
  ["Noida", "Sector 75", "Dasnac Burj Noida"],
  ["Noida", "Sector 75", "Dasnac The Jewel of Noida"],
  ["Noida", "Sector 75", "Apex Athena"],
  ["Noida", "Sector 75", "Panchsheel Pratishtha"],
  ["Noida", "Sector 75", "Gardenia Gateway"],
  ["Noida", "Sector 75", "Maxblis White House"],
  ["Noida", "Sector 75", "JM Aroma"],
  ["Noida", "Sector 75", "Aims Golf Avenue 2"],
  ["Noida", "Sector 75", "Aims Golf Avenue"],
  ["Noida", "Sector 75", "Indosam75"],
  ["Noida", "Sector 75", "Maxblis Grand Wellington"],
  ["Noida", "Sector 75", "Maxblis Grand Kingston"],
  ["Noida", "Sector 76", "Amrapali Silicon City"],
  ["Noida", "Sector 76", "Amrapali Crystal Homes"],
  ["Noida", "Sector 76", "Amrapali Princely Estate"],
  ["Noida", "Sector 76", "Skytech Matrott"],
  ["Noida", "Sector 76", "Amarpali Scilion City"],
  ["Noida", "Sector 76", "JM Orchid"],
  ["Noida", "Sector 76", "Sethi Max Royal"],
  ["Noida", "Sector 76", "Aditya Celebrity Homes"],
  ["Noida", "Sector 77", "Prateek Wisteria"],
  ["Noida", "Sector 77", "Express Zenith"],
  ["Noida", "Sector 77", "Antriksh Forest"],
  ["Noida", "Sector 77", "Griha Pravesh"],
  ["Noida", "Sector 77", "Elite Homz"],
  ["Noida", "Sector 77", "Civitech Sampriti"],
  ["Noida", "Sector 77", "Antriksh Kanball 3G"],
  ["Noida", "Sector 77", "AVS Orchard"],
  ["Noida", "Sector 78", "Mahagun Moderne"],
  ["Noida", "Sector 78", "The Hyde Park"],
  ["Noida", "Sector 78", "Mahagun Mezzaria"],
  ["Noida", "Sector 78", "Antriksh Golf View 2"],
  ["Noida", "Sector 78", "Sikka Karmic Greens"],
  ["Noida", "Sector 78", "Antriksh Golf View"],
  ["Noida", "Sector 78", "Aditya Urban Casa"],
  ["Noida", "Sector 78", "Assotech Windsor Court"],
  ["Noida", "Sector 78", "Sunshine Helios"],
  ["Noida", "Sector 79", "Gaur Sports Wood"],
  ["Noida", "Sector 79", "Elite Golf Greens"],
  ["Noida", "Sector 79", "Civitech Stadia"],
  ["Noida", "Sector 79", "Mahagun Mirabella"],
  ["Noida", "Sector 82", "AWHO Vivek Vihar"],
  ["Noida", "Sector 82", "CGEWHO Kendriya Vihar 2"],
  ["Noida", "Sector 93", "Parsvnath Prestige"],
  ["Noida", "Sector 93", "Purvanchal Silver City"],
  ["Noida", "Sector 93", "Express View Apartments"],
  ["Noida", "Sector 93", "Parsvnath Srishti"],
  ["Noida", "Sector 93 A", "ATS Greens Village"],
  ["Noida", "Sector 93 A", "Supertech Emerald Court"],
  ["Noida", "Sector 93 A", "Eldeco Utopia"],
  ["Noida", "Sector 93 A", "Eldeco Olympia"],
  ["Noida", "Sector 93 B", "Grand Omaxe"],
  ["Noida", "Sector 93 B", "Omaxe The Forest Spa"],
  ["Noida", "Sector 94", "Supertech Supernova"],
  ["Noida", "Sector 99", "Green View Apartment"],
  ["Noida", "Sector Chi 3", "Stellar Icon Apartments"],
  ["Noida", "Sector Chi 3", "Unitech Heights"],
  ["Noida", "Sector Chi 4", "ATS Greens Paradiso"],
  ["Noida", "Sector Chi 5", "Purvanchal Royal City"],
  ["Noida", "Sector Chi 5", "Nimbus Express Park View 2"],
  ["Noida", "Sector Chi 5", "Nimbus Express Park View 2 Low Rise"],
  ["Noida", "Sector Chi 5", "Proview Technocity Apartments"],
  ["Noida", "Sector Chi 5", "AWHO Gurjinder Vihar"],
  ["Noida", "Sector Chi 5", "Express Park View 1"],
  ["Noida", "Sector Chi 5", "Earthcon Casagrand"],
  ["Noida", "Sector Chi 5", "Casagrand 2"],
  ["Noida", "Sector Mu", "Omaxe Palm Greens"],
  ["Noida", "Sector MU 2", "BHS 16 Scheme"],
  ["Noida", "Sector MU 2", "GNIDA BHS 16"],
  ["Noida", "Sector MU 2", "BHS 10 Scheme"],
  ["Noida", "Sector Omega 1", "Today Kings Park"],
  ["Noida", "Sector Omega 1", "Parsvnath Estate"],
  ["Noida", "Sector Omicron 1", "Gaur Atulyam"],
  ["Noida", "Sector Omicron 1", "Supertech Czar Suites"],
  ["Noida", "Sector Omicron 1", "Eldeco Mystic Greens"],
  ["Noida", "Sector Omicron 1", "Sankalp Society"],
  ["Noida", "Sector Omicron 1", "GNIDA Lohiya Enclave"],
  ["Noida", "Sector Omicron 3", "Migsun Ultimo"],
  ["Noida", "Sector Omicron 3", "Uppal Plumeria Garden Estate"],
  ["Noida", "Sector Omicron 3", "Stellar MI Citihomes"],
  ["Noida", "Sector Omicron 3", "Lotus Welfare Society"],
  ["Noida", "Sector P4", "CGEWHO Phase 1"],
  ["Noida", "Sector P4", "Jalvayu Vihar"],
  ["Noida", "Sector Phi 2", "Anand Ashray"],
  ["Noida", "Sector Phi 2", "Novelty Himsagar Apartments"],
  ["Noida", "Sector Pi", "Eldeco Green Meadows"],
  ["Noida", "Sector Pi 1", "Eldeco Residency Greens"],
  ["Noida", "Sector Pi 1", "Gulmohar Estate"],
  ["Noida", "Sector Pi 2", "Unitech Horizon"],
  ["Noida", "Sector Pi 2", "Purvanchal Silver City 2"],
  ["Noida", "Sector Pi 2", "Unitech Habitat"],
  ["Noida", "Sector Pi 2", "Unitech Cascades"],
  ["Noida", "Sector ZETA", "Paramount Golfforeste"],
  ["Noida", "Sector ZETA 1", "ATS Dolce"],
  ["Noida", "Sector ZETA 1", "ACE Platinum"],
  ["Noida", "Sector ZETA 1", "Purvanchal Heights"],
  ["Noida", "Sector ZETA 1", "Amrapali Grand"],
  ["Noida", "Sector ZETA 1", "AVJ Heightss"],
  ["Noida", "Sector ZETA 1", "Assotech Springfields"],
  ["Noida", "Sector-12", "Victoryone Central"],
  ["Noida", "Sector-12", "SKA Green Mansion"],
  ["Noida", "Sector-12", "Civitech Strings"],
  ["Noida", "Sector-12", "Fusion The Brook"],
  ["Noida", "Sector-12", "Fusion The Rivulet"],
  ["Noida", "Sigma 4", "Royal Apartments"],
  ["Noida", "Site B", "Migsun Green Mansion"],
  ["Noida", "Site C", "Oasis Venetia Heights"],
  ["Noida", "Site C", "Dasnac Designarch eHomes"],
  ["Noida", "Surajpur", "Arenaa Heights Surajpur"],
  ["Noida", "Surajpur", "Property Ultima Allure"],
  ["Noida", "Surajpur", "Newtech La Galaxia"],
  ["Noida", "Techzone 4 West", "Gaur Saundaryam"],
  ["Noida", "Techzone 4 West", "Nirala Estate"],
  ["Noida", "Techzone 4 West", "NBCC Aspire Dream Valley"],
  ["Noida", "Techzone 4 West", "Amrapali Terrace Homes"],
  ["Noida", "Techzone 4 West", "Amrapali Centurian Park"],
  ["Noida", "Techzone 4 West", "ABA Cherry County"],
  ["Noida", "Techzone 4 West", "Fusion Homes"],
  ["Noida", "Techzone 4 West", "Saviour Greenarch"],
  ["Noida", "Techzone 4 West", "Nirala Estate Phase 2"],
  ["Noida", "Techzone 4 West", "Himalaya Pride"],
  ["Noida", "Techzone 4 West", "NBCC Leisure Park"],
  ["Noida", "Techzone 4 West", "Apex Splendour"],
  ["Noida", "Techzone 4 West", "Samridhi Grand Avenue"],
  ["Noida", "Techzone 4 West", "Hawelia Valenova Park"],
  ["Noida", "Techzone 4 West", "La Residentia"],
  ["Noida", "Techzone 4 West", "JM Florence"],
  ["Noida", "Techzone 4 West", "Habitech Panchtatva"],
  ["Noida", "Techzone 4 West", "Amrapali Enchante"],
  ["Noida", "Techzone 4 West", "Pigeon Spring Meadows"],
  ["Noida", "Techzone 4 West", "Amrapali Riverview"],
  ["Noida", "Techzone 4 West", "Royal Nest"],
  ["Noida", "Techzone 4 West", "Mangalya Novena Green"],
  ["Noida", "Techzone 4 West", "Patel Neotown"],
  ["Noida", "Techzone 4 West", "O2 Valley"],
  ["Noida", "Techzone 4 West", "CRC Joyous"],
  ["Noida", "Techzone 4 West", "Omkar Royal Nest"],
  ["Noida", "Techzone 4 West", "Supercity Mayfair Residency"],
  ["Noida", "Techzone 4 West", "La Residentia Amrapali"],
  ["Noida", "Techzone 4 West", "Elegant Ville"],
  ["Noida", "Techzone 4 West", "KVD Wind Park"],
  ["Noida", "Techzone 4,Amrapali Leisure Valley", "Ace Aspire"],
  ["Noida", "West", "Supertech Eco Village 1"],
  ["Noida", "West", "Amrapali Verona Heights"],
  ["Noida", "West", "Amrapali Dream Valley Villas"],
  ["Noida", "West", "Himalya Pride"],
  ["Noida", "West", "Mahagun"],
  ["Noida", "Yamuna Expressway", "Gaur Yamuna City 16th Park View"],
  ["Noida", "Yamuna Expressway", "ATS Allure"],
  ["Noida", "Yamuna Expressway", "Gaur Yamuna City"],
  ["Noida", "Yamuna Expressway", "Royal Hometown Beetle Lap"],
  ["Noida", "Yamuna Expressway", "Yamuna Expressway Authority Flat"],
  ["Noida", "Yamuna Expressway", "Ajnara Panorama"],
  ["Noida", "Yamuna Expressway", "Solitairian City"],
  ["Noida", "Yamuna Expressway", "Supertech Golf Country"],

  // ── GHAZIABAD ──
  ["Ghaziabad", "Abhay Khand 2", "Gaur Green Avenue"],
  ["Ghaziabad", "Ahinsa Khand 1", "ATS Advantage"],
  ["Ghaziabad", "Ahinsa Khand 1", "ABA Corp Orange County"],
  ["Ghaziabad", "Ahinsa Khand 1", "Shipra Krishna Vista"],
  ["Ghaziabad", "Ahinsa Khand 1", "Rajhans Premier Apartment"],
  ["Ghaziabad", "Ahinsa Khand 1", "Shipra Srishti"],
  ["Ghaziabad", "Ahinsa Khand 1", "Jaipurias Sunrise Greens"],
  ["Ghaziabad", "Ahinsa Khand 2", "Niho Scottish Garden"],
  ["Ghaziabad", "Ahinsa Khand 2", "Trine Towers"],
  ["Ghaziabad", "Ahinsa Khand 2", "Angel Jupiter"],
  ["Ghaziabad", "Ahinsa Khand 2", "Saya Zenith"],
  ["Ghaziabad", "Ahinsa Khand 2", "Ashiana Greens"],
  ["Ghaziabad", "Ahinsa Khand 2", "Apex D Rio"],
  ["Ghaziabad", "Ahinsa Khand 2", "Ashiana Upvan"],
  ["Ghaziabad", "Ahinsa Khand 2", "Gaur Valerio"],
  ["Ghaziabad", "Ahinsa Khand 2", "SVP Gulmohur Residency"],
  ["Ghaziabad", "Ahinsa Khand 2", "Exotica Elegance"],
  ["Ghaziabad", "Ahinsa Khand 2", "Divyansh Pratham"],
  ["Ghaziabad", "Ahinsa Khand 2", "JKG Amba G Residency"],
  ["Ghaziabad", "Ahinsa Khand 2", "Shri Balaji Residency"],
  ["Ghaziabad", "Ahinsa Khand 2", "Manchanda East End Apartments"],
  ["Ghaziabad", "Ahinsa Khand 2", "Oxirich Avenue"],
  ["Ghaziabad", "Ahinsa Khand 2", "Charms Solitaire"],
  ["Ghaziabad", "Ahinsa Khand 2", "Nirala Eden Park"],
  ["Ghaziabad", "Ahinsa Khand 2", "Saya Desire Residency"],
  ["Ghaziabad", "Ahinsa Khand 2", "Vashisth Vijaya Apartment"],
  ["Ghaziabad", "Ahinsa Khand 2", "Himalayan Towers"],
  ["Ghaziabad", "Ankur Vihar", "DLF Ankur Vihar"],
  ["Ghaziabad", "Ankur Vihar", "Rail Vihar"],
  ["Ghaziabad", "Ankur Vihar", "SLF Ved Vihar"],
  ["Ghaziabad", "Bamheta", "Aditya Luxuria Estate"],
  ["Ghaziabad", "Bhopura", "Bharat City"],
  ["Ghaziabad", "Bhopura", "Super Realtech Oxy Homez"],
  ["Ghaziabad", "Bhopura", "Andromida Planet One"],
  ["Ghaziabad", "Bhopura", "MR Delhi 99"],
  ["Ghaziabad", "Bhopura", "DLF Dilshad Ext Sahibabad"],
  ["Ghaziabad", "Crossing Republik", "Panchsheel Wellington"],
  ["Ghaziabad", "Crossing Republik", "Paramount Symphony"],
  ["Ghaziabad", "Crossing Republik", "Ajnara Gen 10"],
  ["Ghaziabad", "Crossing Republik", "Mahagun Mascot"],
  ["Ghaziabad", "Crossing Republik", "Supertech Livingston"],
  ["Ghaziabad", "Crossing Republik", "GH7 Crossings Republik"],
  ["Ghaziabad", "Crossing Republik", "Assotech The Nest"],
  ["Ghaziabad", "Crossing Republik", "Gardenia Square 1"],
  ["Ghaziabad", "Crossing Republik", "GH 7"],
  ["Ghaziabad", "Crossing Republik", "Gaur Global Village"],
  ["Ghaziabad", "Crossing Republik", "Bulland Heights"],
  ["Ghaziabad", "Crossing Republik", "Prateek The Royal Cliff"],
  ["Ghaziabad", "Crossing Republik", "Proview Laboni Apartments"],
  ["Ghaziabad", "Crossing Republik", "Prabhat Heights"],
  ["Ghaziabad", "Crossing Republik", "Saviour IRIS"],
  ["Ghaziabad", "Crossing Republik", "Arocon Golf Ville"],
  ["Ghaziabad", "Crossing Republik", "Exotica Eastern Court"],
  ["Ghaziabad", "Crossing Republik", "Renowned Srishti"],
  ["Ghaziabad", "Crossing Republik", "Skytech Merion Residency"],
  ["Ghaziabad", "Crossing Republik", "Sam Clement City"],
  ["Ghaziabad", "Crossing Republik", "Dreamland The Willows"],
  ["Ghaziabad", "Crossing Republik", "KSN Golf Greens"],
  ["Ghaziabad", "Crossing Republik", "Arihant Ambience"],
  ["Ghaziabad", "Crossing Republik", "Balaji Foster Heights"],
  ["Ghaziabad", "Crossing Republik", "SKB Gold Coast"],
  ["Ghaziabad", "Duhai", "Landcraft MetroHomes"],
  ["Ghaziabad", "Dundahera", "Amrapali Empire"],
  ["Ghaziabad", "Dundahera", "Keltech Kumar Golf Vista"],
  ["Ghaziabad", "Dundahera", "Cosmos Golden Heights"],
  ["Ghaziabad", "Govind Puram", "Balaji Enclave"],
  ["Ghaziabad", "Gyan Khand 3", "Shipra Riviera"],
  ["Ghaziabad", "Indirapuram", "Cloud 9"],
  ["Ghaziabad", "Indirapuram", "Parsvnath Majestic"],
  ["Ghaziabad", "Indirapuram", "Angel Mercury Indirapuram"],
  ["Ghaziabad", "Indirapuram", "MKS La Royale"],
  ["Ghaziabad", "Indirapuram", "Pinnacle Towers"],
  ["Ghaziabad", "Indirapuram", "Ramprastha Imperial Heights"],
  ["Ghaziabad", "Indirapuram", "Amrapali Village 2"],
  ["Ghaziabad", "Indirapuram", "Arihant Harmony"],
  ["Ghaziabad", "Indirapuram", "Rishabh Cloud9 Skylish Towers"],
  ["Ghaziabad", "Indirapuram", "Shipra Sun Tower"],
  ["Ghaziabad", "Indirapuram", "Shipra Windsor and Nova Society"],
  ["Ghaziabad", "Indirapuram", "Independent Builder Floors Indirapuram"],
  ["Ghaziabad", "Indirapuram", "Gaur Greenvista"],
  ["Ghaziabad", "Indirapuram", "Shipra Suncity Regent"],
  ["Ghaziabad", "Indirapuram", "GDA Flats Indirapuram"],
  ["Ghaziabad", "Judges Enclave", "JNC Princess Park"],
  ["Ghaziabad", "Judges Enclave", "Arihant Residency"],
  ["Ghaziabad", "Judges Enclave", "Exotica East Square"],
  ["Ghaziabad", "Lajpat Nagar", "GDA Flats"],
  ["Ghaziabad", "Loni", "UPAVP Mandola Vihar Apartment"],
  ["Ghaziabad", "Madhuban Bapudham", "GDA Madhuban Bapu Dham Society"],
  ["Ghaziabad", "Mehrauli", "Rise Organic Homes"],
  ["Ghaziabad", "Mehrauli", "Mahagun Puram Phase 2"],
  ["Ghaziabad", "Mehrauli", "Ruchira Sapphire Plaza"],
  ["Ghaziabad", "Mohan Nagar", "Parsvnath Paradise"],
  ["Ghaziabad", "Mohan Nagar", "Saviour Park"],
  ["Ghaziabad", "Morta", "Moti Residency"],
  ["Ghaziabad", "NH 24 Highway", "Landcraft Golflinks"],
  ["Ghaziabad", "NH 24 Highway", "Mahagun Puram"],
  ["Ghaziabad", "NH 24 Highway", "Wave Dream Homes"],
  ["Ghaziabad", "NH 24 Highway", "Aditya City Apartments"],
  ["Ghaziabad", "NH 24 Highway", "Aditya Urban Homes"],
  ["Ghaziabad", "NH 24 Highway", "Divyansh Onyx"],
  ["Ghaziabad", "NH 24 Highway", "Wave Veridia Oakwood Enclave"],
  ["Ghaziabad", "NH 24 Highway", "Urban Homes Aditya World City"],
  ["Ghaziabad", "NH 24 Highway", "Aditya City Grace"],
  ["Ghaziabad", "NH 24 Highway", "Aditya World City"],
  ["Ghaziabad", "NH 24 Highway", "Savfab Jasmine Grove"],
  ["Ghaziabad", "NH 24 Highway", "Skardi Greens"],
  ["Ghaziabad", "NH 24 Highway", "Wave Executive Floors"],
  ["Ghaziabad", "NH 24 Highway", "Parakh The Golden Gate"],
  ["Ghaziabad", "NH 24 Highway", "Wave City Dream Homes Ghaziabad"],
  ["Ghaziabad", "NH 24 Highway", "VVIP Namah"],
  ["Ghaziabad", "NH 24 Highway", "Marina Suites"],
  ["Ghaziabad", "NH 24 Highway", "Wave City"],
  ["Ghaziabad", "NH 24 Highway", "Wave Swamanorath"],
  ["Ghaziabad", "NH 24 Highway", "Sapphire Smart Homes"],
  ["Ghaziabad", "NH 24 Highway", "Aditya World City Urban Royal"],
  ["Ghaziabad", "NH 24 Highway", "Wave Eligo"],
  ["Ghaziabad", "NH 24 Highway", "Unione Residency"],
  ["Ghaziabad", "NH 24 Highway", "Agarwal The Resort"],
  ["Ghaziabad", "NH 24 Highway", "Landcraft Golf Link Apartments"],
  ["Ghaziabad", "Nyay Khand 1", "Gaur Green Vista"],
  ["Ghaziabad", "Nyay Khand 1", "Supertech Icon"],
  ["Ghaziabad", "Nyay Khand 1", "V3S Indralok"],
  ["Ghaziabad", "Nyay Khand 2", "Amrapali Village"],
  ["Ghaziabad", "Pratap Vihar", "UPHD Ganga Yamuna and Hindon Apartment"],
  ["Ghaziabad", "Raj Nagar Extension", "VVIP Addresses"],
  ["Ghaziabad", "Raj Nagar Extension", "KW Srishti"],
  ["Ghaziabad", "Raj Nagar Extension", "Eureka Diya Greencity"],
  ["Ghaziabad", "Raj Nagar Extension", "SVP Gulmohur Garden"],
  ["Ghaziabad", "Raj Nagar Extension", "Charms Castle"],
  ["Ghaziabad", "Raj Nagar Extension", "Landcraft River Heights"],
  ["Ghaziabad", "Raj Nagar Extension", "Nilaya Greens"],
  ["Ghaziabad", "Raj Nagar Extension", "Windsor Paradise 2"],
  ["Ghaziabad", "Raj Nagar Extension", "Javin Raj Empire"],
  ["Ghaziabad", "Raj Nagar Extension", "Star Rameshwaram"],
  ["Ghaziabad", "Raj Nagar Extension", "SCC Sapphire"],
  ["Ghaziabad", "Raj Nagar Extension", "Mittal Rajnagar Residency"],
  ["Ghaziabad", "Raj Nagar Extension", "Addela Palm Resort"],
  ["Ghaziabad", "Raj Nagar Extension", "Ajnara Integrity"],
  ["Ghaziabad", "Raj Nagar Extension", "Gaur Cascades"],
  ["Ghaziabad", "Raj Nagar Extension", "Ascent Savy Ville De"],
  ["Ghaziabad", "Raj Nagar Extension", "MCC Signature Heights"],
  ["Ghaziabad", "Raj Nagar Extension", "KDPMGI Gharaunda"],
  ["Ghaziabad", "Raj Nagar Extension", "Shourya Aura Chimera"],
  ["Ghaziabad", "Raj Nagar Extension", "Ashiana Palm Court"],
  ["Ghaziabad", "Raj Nagar Extension", "Aggarwal Heights"],
  ["Ghaziabad", "Raj Nagar Extension", "Emenox Brave Hearts"],
  ["Ghaziabad", "Raj Nagar Extension", "VVIP Mangal"],
  ["Ghaziabad", "Raj Nagar Extension", "SG Grand"],
  ["Ghaziabad", "Raj Nagar Extension", "Meenal Balmukanda Residency"],
  ["Ghaziabad", "Raj Nagar Extension", "Highend Paradise"],
  ["Ghaziabad", "Raj Nagar Extension", "MR Platinum 321"],
  ["Ghaziabad", "Raj Nagar Extension", "Uninav Heights"],
  ["Ghaziabad", "Raj Nagar Extension", "Vasu Fortune Residency"],
  ["Ghaziabad", "Raj Nagar Extension", "Devika Skypers"],
  ["Ghaziabad", "Raj Nagar Extension", "Uninav Utopia"],
  ["Ghaziabad", "Raj Nagar Extension", "KDP Grand Savanna"],
  ["Ghaziabad", "Raj Nagar Extension", "SCC Heights"],
  ["Ghaziabad", "Raj Nagar Extension", "Himalaya Tanishq"],
  ["Ghaziabad", "Raj Nagar Extension", "MR Proview Officer City 2"],
  ["Ghaziabad", "Raj Nagar Extension", "Shree Energy Classic Residency"],
  ["Ghaziabad", "Raj Nagar Extension", "Migsun Roof"],
  ["Ghaziabad", "Raj Nagar Extension", "Sg Impression 58"],
  ["Ghaziabad", "Raj Nagar Extension", "Royce Sentosa Parc"],
  ["Ghaziabad", "Raj Nagar Extension", "LR Bluemoon Homes"],
  ["Ghaziabad", "Raj Nagar Extension", "Techmans Moti Residency"],
  ["Ghaziabad", "Raj Nagar Extension", "Value Meadows Vista"],
  ["Ghaziabad", "Raj Nagar Extension", "Divyansh Arc Angels"],
  ["Ghaziabad", "Raj Nagar Extension", "Proview Officer City"],
  ["Ghaziabad", "Raj Nagar Extension", "KM Residency"],
  ["Ghaziabad", "Raj Nagar Extension", "Mehak Jeevan"],
  ["Ghaziabad", "Raj Nagar Extension", "Uninav Bliss"],
  ["Ghaziabad", "Raj Nagar Extension", "Raj Garden City"],
  ["Ghaziabad", "Ramprastha", "Ramprastha Colony"],
  ["Ghaziabad", "Ramprastha", "JM Park Sapphire"],
  ["Ghaziabad", "Ramprastha Greens", "Ramprastha Pearl Court"],
  ["Ghaziabad", "Ramprastha Greens", "Ramprastha Platinum Height"],
  ["Ghaziabad", "Ramprastha Greens", "Gulshan GC Emerald Heights"],
  ["Ghaziabad", "Sain Vihar", "Saviour Greenisle"],
  ["Ghaziabad", "Sector 1 Vaishali", "Rishabh Cloud 9 Towers"],
  ["Ghaziabad", "Sector 1 Vaishali", "Express Green Apartment Sector 1 Vaishali"],
  ["Ghaziabad", "Sector 13 Vasundhara", "SKG The Merlin"],
  ["Ghaziabad", "Sector 14 Vasundhara", "Express One"],
  ["Ghaziabad", "Sector 15 Vasundhara", "Nandini The Vasundhara Grand"],
  ["Ghaziabad", "Sector 18 Vasundhara", "Elite Estate"],
  ["Ghaziabad", "Sector 2C Vasundhara", "Metro Suites Glitz"],
  ["Ghaziabad", "Sector 3 Vaishali", "Apex Acacia Valley"],
  ["Ghaziabad", "Sector 3 Vasundhara", "SG Homes"],
  ["Ghaziabad", "Sector 3 Vasundhara", "Gardenia Glamour"],
  ["Ghaziabad", "Sector 3 Vasundhara", "Sarvottam KSN Square"],
  ["Ghaziabad", "Sector 3 Vasundhara", "JNC Greenwoods"],
  ["Ghaziabad", "Sector 4 Vaishali", "Nandini Metro Suites"],
  ["Ghaziabad", "Sector 4 Vaishali", "Eldeco Apartments"],
  ["Ghaziabad", "Sector 4 Vaishali", "Mahagun Villa"],
  ["Ghaziabad", "Sector 4 Vaishali", "Mahagun Mosaic"],
  ["Ghaziabad", "Sector 4 Vaishali", "Devika Apartments"],
  ["Ghaziabad", "Sector 4 Vaishali", "Surya Kanishk Tower"],
  ["Ghaziabad", "Sector 4 Vaishali", "Express Apartments"],
  ["Ghaziabad", "Sector 4 Vaishali", "Leela Homes"],
  ["Ghaziabad", "Sector 4 Vaishali", "Amrapali Apartments"],
  ["Ghaziabad", "Sector 4 Vaishali", "Gaur Heights"],
  ["Ghaziabad", "Sector 4 Vaishali", "Gaur Ganga"],
  ["Ghaziabad", "Sector 4C Vasundhara", "CGHS Vartalok Apartments"],
  ["Ghaziabad", "Sector 5 Vaishali", "Supertech Avant Garde"],
  ["Ghaziabad", "Sector 5 Vaishali", "Ansals Neelpadam 1"],
  ["Ghaziabad", "Sector 5 Vaishali", "Supertech Residency"],
  ["Ghaziabad", "Sector 5 Vasundhara", "ABA Olive County"],
  ["Ghaziabad", "Sector 9 Vaishali", "Civitech Florencia"],
  ["Ghaziabad", "Shahpur Bamheta", "Aditya World City Urban Homes"],
  ["Ghaziabad", "Shakti Khand 4", "Real World Residency"],
  ["Ghaziabad", "Shalimar garden", "SVP Gulmohar Garden Phase 2"],
  ["Ghaziabad", "Shalimar Garden Extension 2", "shalimargarden ext ii ghaziabad"],
  ["Ghaziabad", "Siddharth Vihar", "Prateek Grand City"],
  ["Ghaziabad", "Siddharth Vihar", "Gaurs Siddhartham"],
  ["Ghaziabad", "Siddharth Vihar", "T Homes"],
  ["Ghaziabad", "Siddharth Vihar", "SG Shikhar Height"],
  ["Ghaziabad", "Siddharth Vihar", "T and T Eutopia"],
  ["Ghaziabad", "Siddharth Vihar", "Apex The Kremlin"],
  ["Ghaziabad", "Siddharth Vihar", "UPAVP Brahmputra Enclave"],
  ["Ghaziabad", "Siddharth Vihar", "Siddharth Vihar Residency"],
  ["Ghaziabad", "Siddharth Vihar", "Truvae Fragrance Homes"],
  ["Ghaziabad", "Vaibhav Khand", "Saya Gold Avenue"],
  ["Ghaziabad", "Vaibhav Khand", "Aditya Mega City"],
  ["Ghaziabad", "Vaibhav Khand", "Krishna Apra Gardens"],
  ["Ghaziabad", "Vaibhav Khand", "Express Garden"],
  ["Ghaziabad", "Vaibhav Khand", "Shipra Sun City"],
  ["Ghaziabad", "Vaibhav Khand", "Mahagun Mansion 1 and 2"],
  ["Ghaziabad", "Vaibhav Khand", "Amrapali Royal"],
  ["Ghaziabad", "Vaibhav Khand", "Assotech Windsor Park"],
  ["Ghaziabad", "Vaibhav Khand", "Gaur Green City"],
  ["Ghaziabad", "Vaibhav Khand", "Gulshan GC Grand"],
  ["Ghaziabad", "Vaibhav Khand", "Panchsheel SPS Residency"],
  ["Ghaziabad", "Vaibhav Khand", "HRC Professional Hub"],
  ["Ghaziabad", "Vaibhav Khand", "Amrapali Green"],
  ["Ghaziabad", "Vaibhav Khand", "Aarcity Krishna Apra Sapphire"],
  ["Ghaziabad", "Vaibhav Khand", "Shipra Neo"],
  ["Ghaziabad", "Vaibhav Khand", "HRC Apartments"],
  ["Ghaziabad", "Vaibhav Khand", "Parsvnath Majestic Arcade"],
  ["Ghaziabad", "Vaishali", "Ramprastha Greens Royal Park"],
  ["Ghaziabad", "Vaishali", "Oasis Emerald Heights"],
  ["Ghaziabad", "Vasundhara", "Gardenia Gitanjali"],
  ["Ghaziabad", "Vasundhara", "Ajpa Dronagiri"],
  ["Ghaziabad", "Vasundhara", "Apex The Florus"],
  ["Ghaziabad", "Vasundhara", "Migsun Kiaan"],
  ["Ghaziabad", "Wave City", "Sanchar Nest Palm Heights"],
  ["Ghaziabad", "Wave City", "Wave Floors"],
];

async function seed() {
  console.log('Seeding society data...');

  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // Clear existing data (safe re-run)
    await client.query('DELETE FROM master_societies');

    // Insert all rows
    const insertSQL = `
      INSERT INTO master_societies (city, locality, society_name)
      VALUES ($1, $2, $3)
      ON CONFLICT (city, locality, society_name) DO NOTHING
    `;

    for (const [city, locality, society] of SOCIETIES) {
      await client.query(insertSQL, [city, locality, society]);
    }

    await client.query('COMMIT');

    // Print summary
    const result = await client.query(`
      SELECT city, COUNT(*) as count 
      FROM master_societies 
      GROUP BY city ORDER BY city
    `);
    console.log('✓ Seeded society data:');
    result.rows.forEach(r => console.log(`  ${r.city}: ${r.count} societies`));
    console.log(`  Total: ${SOCIETIES.length} rows`);

  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Seed failed:', err.message);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

if (require.main === module) {
  seed().catch(() => process.exit(1));
}

module.exports = { seed, SOCIETIES };
